### ISSUE TITLE
請支援 sl 指令

### ISSUE THREAD

**Issue by johnroyer** [CQD/xkcd.tw#13]
在 `/s/uni/index.html` 已實作了 `ls`, `cat` 等指令及功能。

希望可以幫 jqery.terminal 實作 `sl` 指令

**Comment by CQD** [comment]
靠邀...XD

**Comment by CQD** [comment]
Fixed，免費加贈 cowsay

**Comment by johnroyer** [comment]
有了 cowsay，是否順便裝一下 fortune XD

**Comment by CQD** [comment]
有趣的東西都裝會裝不完啦 XD
