### ISSUE TITLE
使用miniflux订阅rss feed无法获取到文章内容

### ISSUE THREAD

**Issue by deletefromuser** [CQD/xkcd.tw#32]
在本地使用docker部署了miniflux之后，可以获取到文章列表，但是打开文章后内容是空白
#### docker-compose.yml
```docker
services:
  miniflux:
    image: ${MINIFLUX_IMAGE:-miniflux/miniflux:latest}
    container_name: miniflux
    restart: always
    ports:
      - "81:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgres://miniflux:secret@db/miniflux?sslmode=disable
      - RUN_MIGRATIONS=1
      - CREATE_ADMIN=1
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=test123
      - DEBUG=1
    # Optional health check:
    healthcheck:
     test: ["CMD", "/usr/bin/miniflux", "-healthcheck", "auto"]
  db:
    image: postgres:15
    container_name: postgres
    environment:
      - POSTGRES_USER=miniflux
      - POSTGRES_PASSWORD=secret
    volumes:
      - miniflux-db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "miniflux"]
      interval: 10s
      start_period: 30s
volumes:
  miniflux-db:
```
尝试了别的博客的[atom feed](http://blog.codingnow.com/atom.xml)，还有[xkcd](https://xkcd.com/rss.xml)，都是没有问题的，

也不是GFW的问题，因为直连[https://xkcd.tw/](https://xkcd.tw/)是没有问题的

添加feed时，试了`Scraper Rules`设置`div#content`和`div#content img`，`Rewrite Rules`设置`add_image_title`，都没有解决，不太清楚是哪里的问题，有人也用miniflux的吗

**Comment by CQD** [comment]
拉 xkcd.com 的 atom feed 出來的內文
<img width="999" alt="圖片" src="https://user-images.githubusercontent.com/94944/233980347-b25c1fcd-fe1a-4a07-a717-6a65ffa17b76.png">


拉 xkcd.tw 的 atom feed 出來的內文
<img width="727" alt="圖片" src="https://user-images.githubusercontent.com/94944/233980571-b9d48621-8319-476a-8db1-571c51f60641.png">


確實不太對...

**Comment by CQD** [comment]
![圖片](https://user-images.githubusercontent.com/94944/233993313-95541f1b-2fdc-4fea-9ea8-f726b9c335bb.png)
拉 DB 內容，一樣是有 entry 沒有內容

`docker compose logs` 一下沒看到什麼奇怪的東西

----

單一 entry 分別長這樣，差別是
- 中文
- 順序
- 圖片多了 height
- 多了 Author


```xml
<entry>
<title>叫床聲很大</title>
<summary type="html">
<img src="https://xkcd.tw/strip/316.png" alt="當然了，球型或拋物面反射器會導致異常性的行為。" height="414" title="當然了，球型或拋物面反射器會導致異常性的行為。"/>
</summary>
<link href="https://xkcd.tw/316"/>
<id>https://xkcd.tw/316</id>
<updated>2023-04-05T15:54:23+08:00</updated>
<author>
<name>CQD</name>
</author>
</entry>
```

```xml
<entry>
<title>Escape Speed</title>
<link href="https://xkcd.com/2765/" rel="alternate"/>
<updated>2023-04-19T00:00:00Z</updated>
<id>https://xkcd.com/2765/</id>
<summary type="html">
<img src="https://imgs.xkcd.com/comics/escape_speed.png" title="Gotta go fast" alt="Gotta go fast" />
</summary>
</entry>
```

另外試著加了 https://blog.gslin.org/feed/atom/ ，可以正常閱讀，所以「繁體中文 + atom」不會觸發。

----

憑直覺是...加上 CDATA 可以解決，當初拔掉 CDATA（ d5836b0 ） 是因為想觸發 feedly 在 XKCD 的 feed 會顯示 hover 按鈕這件事。

但真的就是直覺，沒有證據，也想驗證一下

**Comment by CQD** [comment]
![圖片](https://user-images.githubusercontent.com/94944/233997819-b8bf93dd-2d04-4b6e-bd74-3419f9c329b8.png)

原因不確定，但本地測試看來 CDATA 是解法（用 XML 包 HTML 也是應該這麼做）。就放棄 feedly 的特殊行為吧。

**Comment by CQD** [comment]
> 單一 entry 分別長這樣，差別是
> -   中文
> -   順序
> -  圖片多了 height
> -  多了 Author

還有一點，xkcd.com 的 feed 的 html 是 escape 過的...開瀏覽器看不出來，手動 curl 才會看到。那這跟 CDATA 就是同一條路。

總之修正也上線了，刪除 feed 重新訂閱應該就能看到。
